# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "dummy"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :aws do |aws,override|

    aws.access_key_id = "KEY ID"
    aws.secret_access_key = "SECRET ACCESS KEY
    aws.keypair_name = "KEY NAME"
    aws.ami = "AMI ID"
    aws.instance_type = "t2.micro"
    aws.region = "REGION"
    aws.subnet_id = "SUBNET ID"
    aws.security_groups = ["SECURITY GROUP ID"]
    aws.associate_public_ip = true

    override.ssh.username = "ubuntu"
  	override.ssh.private_key_path = "MY PRIVATE KEY PATH"

  end
end
